### ISSUE TITLE
Is it possible pass params to validator?

### ISSUE THREAD

**Issue by antonmoiseev** [PolymerElements/iron-validator-behavior#18]
Is it possible to pass params to validator? In the example below the length is the parameter I would want to configure for the validator:

``` js
Polymer({
  is: 'ssn-validator',

  behaviors: [
    Polymer.IronValidatorBehavior
  ],

  properties: {
    length: {
      type: Number,
      notify: false,
      value: 9
    }
  },

  validate(ssn) {
    let regex;
    switch (this.length) {
      case 4: regex = /^\d{4}/; break;
      case 6: regex = /^\d{2}-\d{4}/; break;
      case 9: regex = /^\d{3}-\d{2}-\d{4}/; break;
      default: throw new Error(`Invalid length value (${this.length}) for SSN validator`);
    }
    return regex.test(ssn);
  }
});
```

However whatever value I set for the length attribute in the HTML, I always get the default value when reading the length property inside the `validate()` method.

``` html
<ssn-validator length="6"></ssn-validator>
```

**Comment by notwaldorf** [comment]
No, I don't think this is possible at this point

**Comment by notwaldorf** [comment]
Going to close this issue -- based on how this element is built, i don't think this will ever work :(

**Comment by akc42** [comment]
Despite this issue being closed as not working, I have it working. Here is some of how I did it.
Firstly - defined my validator.  PAS.ADMIN_USER is a global string setup during the user login session of the logon name of the super user to the app.  They can't edit their logon name from this fixed value, otherwise we insist on three characters. 

```
<dom-module id="pas-profile-user-validator">
  <template></template>
  <script>
  Polymer({
    is: 'pas-profile-user-validator',
    behaviors: [Polymer.IronValidatorBehavior],
    properties: {
      uid: {
        type: Number,
        value: 0
      }
    },
    validate: function(value) {
      if (/^\w{3,}$/.test(value)) {
        if (this.uid === 0 && value !== PAS.ADMIN_USER) {
          return false;
        }
        return true;
      }
      return false;
    }
  });
  </script>
</dom-module>
```

Then use it inside the module which also has a paper input that I am going to validate with data binding to bring properties across from surrounding element. "User" is an Object property defined by the PAS.User behavior and will contain lots of info about the current logged in user, including user.uid (which is the key info here). NOTE: I have other fields validating in a similar way not shown (behind the ...)

```
<dom-module id="pas-profile">
  <template>
    <style>...</style>
    <pas-profile-user-validator uid="[[user.uid]]"></pas-profile-user-validator>
    <paper-card id="profile" heading="User Profile Edit">
      <div class="card-content">
        <form id="doprofile" is="iron-form" action="/api/profile" method="POST" content-type="application/json">
          <input type="hidden" value="[[user.uid]]" name="uid"/>
          <paper-input
            id="dn"
            label="Logon Name"
            error-message="Min 3 characters"
            required
            name="username"
            validator="pas-profile-user-validator"
            value="[[user.logonname]]"></paper-input>
 ...
        </form>
... (more stuff including ability to submit form)
      </div>
    </paper-card>
  </template>

  <script>
    Polymer({
      is: 'pas-profile',
      behaviors: [
        Polymer.IronValidatorBehavior,
        PAS.User
      ],
      listeners: {
        'dn.blur': '_unValidate'
      },
      _unValidate: function() {
        this.$.dn.validate();
      }
    });
  </script>
</dom-module>
```

As @antonmoiseev requries, length could be a bound property that is connected to the property in the surrounding element and it could be manipulated by the functions in the surrounding element.
